### PR TITLE
MTS-417 Update example scripts to account for new API changes

### PR DESCRIPTION
**Pull request by obukatar**
https://leia3d.atlassian.net/browse/MTS-417

* Add the example scripts using the Leia Storage API.
* Updated the README.

Also FYI:
https://github.com/LeiaInc/MediaCloudRESTAPI/pull/91

### CODE REVIEW

**Review by vit-lebediev — COMMENTED** [review]
Good job! But let's wait until we merge & release changes to storage API.

**Review by Flox06 — APPROVED** [review]

**Comment by vit-lebediev** [comment]
I'll move it to draft to indicate that it should not be reviewed just yet

**Review by vit-lebediev — APPROVED** [review]
GTG with small suggestion.

**Review by vit-lebediev — APPROVED** [review]
GTG

**Pull request merged**
